---
title: "About Me"
---
I am proud to call East Nashville my home. It's the best neighborhood on the planet.

Yes there really is a Kalamazoo. It's where I'm from.

<p></br></p>

###I nerd out over:
* Renovating my home  
* Ice skating  
* The tv show Chuck  
* Traveling  
* Structural Equation Models  
* Lake Michigan  

My newest thing is ... Crossfit. Ouch.
<p></br></p>
###Countries I've Visited
<!--html_preserve-->
<script src="https://www.amcharts.com/lib/3/ammap.js" type="text/javascript"></script>
<script src="https://www.amcharts.com/lib/3/maps/js/worldHigh.js" type="text/javascript"></script>
<script src="https://www.amcharts.com/lib/3/themes/dark.js" type="text/javascript"></script>
<div id="mapdiv" style="width: 800px; height: 450px;"></div>
<div style="width: 800px; font-size: 70%; padding: 5px 0; text-align: center; background-color: #C9D2F0; margin-top: 1px; color: #686869;"><a href="https://www.amcharts.com/visited_countries/" style="color: #686869;">Create your own visited countries map</a> or check out the <a href="https://www.amcharts.com/" style="color: #686869;">JavaScript Charts</a>.</div>
<script type="text/javascript">
var map = AmCharts.makeChart("mapdiv",{
type: "map",
theme: "dark",
projection: "mercator",
panEventsEnabled : true,
backgroundColor : "#C9D2F0",
backgroundAlpha : 1,
zoomControl: {
zoomControlEnabled : false
},
dataProvider : {
map : "worldHigh",
getAreasFromMap : true,
areas :
[
	{
		"id": "AT",
		"showAsSelected": true
	},
	{
		"id": "BE",
		"showAsSelected": true
	},
	{
		"id": "CH",
		"showAsSelected": true
	},
	{
		"id": "CZ",
		"showAsSelected": true
	},
	{
		"id": "DE",
		"showAsSelected": true
	},
	{
		"id": "ES",
		"showAsSelected": true
	},
	{
		"id": "FR",
		"showAsSelected": true
	},
	{
		"id": "GB",
		"showAsSelected": true
	},
	{
		"id": "HU",
		"showAsSelected": true
	},
	{
		"id": "IT",
		"showAsSelected": true
	},
	{
		"id": "LU",
		"showAsSelected": true
	},
	{
		"id": "NL",
		"showAsSelected": true
	},
	{
		"id": "PT",
		"showAsSelected": true
	},
	{
		"id": "RO",
		"showAsSelected": true
	},
	{
		"id": "SI",
		"showAsSelected": true
	},
	{
		"id": "SK",
		"showAsSelected": true
	},
	{
		"id": "VA",
		"showAsSelected": true
	},
	{
		"id": "GI",
		"showAsSelected": true
	},
	{
		"id": "CA",
		"showAsSelected": true
	},
	{
		"id": "MX",
		"showAsSelected": true
	},
	{
		"id": "US",
		"showAsSelected": true
	},
	{
		"id": "BR",
		"showAsSelected": true
	},
	{
		"id": "PE",
		"showAsSelected": true
	},
	{
		"id": "VE",
		"showAsSelected": true
	},
	{
		"id": "ET",
		"showAsSelected": true
	},
	{
		"id": "GH",
		"showAsSelected": true
	},
	{
		"id": "KE",
		"showAsSelected": true
	},
	{
		"id": "MA",
		"showAsSelected": true
	},
	{
		"id": "NA",
		"showAsSelected": true
	},
	{
		"id": "NG",
		"showAsSelected": true
	},
	{
		"id": "SZ",
		"showAsSelected": true
	},
	{
		"id": "ZA",
		"showAsSelected": true
	},
	{
		"id": "AE",
		"showAsSelected": true
	},
	{
		"id": "CN",
		"showAsSelected": true
	},
	{
		"id": "JP",
		"showAsSelected": true
	},
	{
		"id": "KP",
		"showAsSelected": true
	},
	{
		"id": "KR",
		"showAsSelected": true
	}
]
},
areasSettings : {
autoZoom : true,
color : "#686869",
colorSolid : "#B82AEB",
selectedColor : "#B82AEB",
outlineColor : "#DBD2DB",
rollOverColor : "#6AE5F5",
rollOverOutlineColor : "#000000"
}
});
</script>
<!--/html_preserve-->  

<p></br></p>

You can contact me at jacquelynpennings@gmail.com.