---
title: "Publications and Grants"
output:
  html_document
---

# {.tabset .tabset-fade .tabset-pill}

## Publications  

[Complete List of Published Work in MyBibliography](https://www.ncbi.nlm.nih.gov/sites/myncbi/jacquelyn.pennings.1/bibliography/52622622/public/?sort=date&direction=ascending) 
<br>

1.	Purvis K, Cross D, Kellermann G, Kellermann M, Huisman H, & **Pennings JS**. (2006). An experimental evaluation of targeted amino acid therapy with behaviorally at-risk children. Journal of Alternative and Complementary Medicine, 11, 591-593. 

2.	Purvis KB, Cross DR, & **Pennings JS**. (2007). International adoption of post-institutionalized children: Implications for school counselors. Journal of School Counseling, 5(22). Retrieved December 3, 2007, from http://www.jsc.montana.edu/articles/v5n22.pdf

3.	Purvis KB, Cross DR, & **Pennings JS**. (2009). Trust-Based Relational Intervention™: Interactive Principles for Adopted Children with Special Social-Emotional Needs. Journal of Humanistic Counseling, Education & Development, 49, 3-22.

4.	Dietz T, Davis D, & **Pennings, JS**. (2012). Evaluating and Comparing the Efficacy of Three Group Therapies for Child Sexual Abuse: The Effect of Incorporating Animal Assisted Therapy, Journal of Child Sexual Abuse, 21(6), 665-683

5.	Rus AV, Stativa E, **Pennings JS**, Cross DR, Ekas N, Purvis K, Parris SR. (2013). Severe Punishment of Children by Staff in Romanian Placement Centers for School-Aged Children: Effects of Child and Institutional Characteristics. Child Abuse and Neglect, 37(12) 1152-1162. 

6.	Stativa E, Rus AV, Suciu N, **Pennings JS**, Butterfield ME, Wenyika R, & Webster R. (2014). Characteristics and prenatal care utilisation of Romanian pregnant women. The European Journal of Contraception and Reproductive Health Care, 19(3), 220-226. 

7.	McFarlane J, **Pennings J**, Symes L, Maddoux J, & Paulson R. (2014). Predicting Abused Women with Children Who Return to the Abuser: Development of a Risk Assessment Tool. Journal of Threat Assessment and Management, 1(4), 274-290

8.	Fredland N, McFarlane J, Symes L, Gilroy H, Paulson R, Nava A, & **Pennings JS**.  (2015). Connecting Partner Violence to Poor Functioning for Women and Children: Modeling Intergenerational Outcomes. Journal of Family Violence, 30(5), 555-566. 

9.	Alexander GK, Rollins K, Walker D, Wong L, & **Pennings J**. (2015). Yoga for self-care and burnout prevention among nurses. Workplace Health & Safety, 63(10), 462-470. 

10.	**Pennings J**, McFarlane J, Paulson R, Fredland N, Binder B, Koci A, Montalvo-Liendo N. (2015). Predicting Behavioral Dysfunctions of Youth Living in Violent Homes: A Rapid Assessment Triage Tool. Journal of Applied Research on Children: Informing Policy for Children at Risk, 6(1), Article 11. 

11.	Daniels G, Robinson JR, Walker C, **Pennings JS**, Anderson ST. (2015). Gastrointestinal Symptoms among African Americans Undergoing Hemodialysis. Nephrology Nursing Journal, 42(6), 539-548. 

12.	McFarlane J, **Pennings J**, Liu FQ, Gilroy H, Nava A, Maddoux J, Montalvo-Liendo N, Paulson R. (2016). Predicting abused women with children who return to a shelter: Development and use of a rapid assessment triage tool. Violence Against Women, 22(2), 189-205

13.	Symes L, Maddous J, McFarlane J, **Pennings J**. (2016). A risk assessment tool to predict sustained PTSD symptoms among women reporting abuse. Journal of Women’s Health, 25(4), 340-347. doi:10.1089/jwh.2015.5287. 

14.	Fredland N, McFarlane J, Symes L, Maddoux J, **Pennings J**, Paulson R, Binder B & Gilroy H. (2016). Modeling the intergenerational impact of partner abuse on maternal and child function at 24 months post outreach: Implications for practice and policy. Nursing Outlook, 64(2), 156-169. doi:10.1016/j.outlook.2015.10.005 

15.	Stativa E, Rus AV, Stanescu A, **Pennings JS**, Parris SR & Wenyika R. (2016). Prevalence and Predictors of Anaemia in Romanian Infants 6-23 Months Old. Journal of Public Health, 38(3), e272-e281. doi:10.1093/pubmed/fdv145 

16.	Rhea DJ, Rivchun AP, & **Pennings J**. (2016). The Liink Project: Implementation of a Recess and Character Development Pilot Study with Grades K & 1 Children. Texas Association of Health, Physical Education, Recreation, & Dance Journal (TAHPERD), 84(2), 14-17.

17.	Rus A, Tomuletiu E, Parris S, **Pennings J**, Webster R. (2016). Comparisons of Emotional and Behavioral Problems Reported by Parents and Teachers in Three Ethnic Groups Living in Romania: A Pilot Study. Review of Research and Social Intervention, 55, 63-79.

18.	Rus A, Stativa E, Butterfield M, **Pennings J**, Parris S, Burcea G, Wenyika R. (2018). Peer Exploitation: Findings from a Romanian Nationally Representative Sample of Children Living in Long-Term Residential Centres. Child Abuse Review, 27(1), 58-71. Doi:10.1002/car.2464. 

19.	Sivaganesan A, Zuckerman S, Khan I, Nian H, Harrell FE, **Pennings JS**, Harbaugh R, Foley KT, Bydon M, Asher AL, Devin CJ, Archer KR. (2018). Predictive Model for Medical and Surgical Readmissions Following Elective Lumbar Spine Surgery: A National Study of 33,674 Patients. Spine, 44(8), 588-600. doi:10.1097/brs.0000000000002883. 

20.	Asher AL, Devin CJ, Weisenthal BM, **Pennings J**, Khan I, Archer KR, Sivaganesan A, Chotai S, Bydon M, Nian H, Harrell FE, McGirt MJ, Pummaneni P, Bisson EF, Shaffrey C, Foley KT. (2019). Effect of Modified Japanese Orthopedic Association Severity Classifications on Satisfaction with Outcomes 12-months after Elective Surgery for Cervical Spine Myelopathy. Spine, 44(11), 801-808. doi: 10.1097/BRS.0000000000002946.

21.	Hills JM, **Pennings JS**, Archer KR, Wick JB, Daryoush J, Butler M, Sivaganesan A, Khan I, Call R, Devin CJ. (2019). Preoperative Opioids and 1-year Patient Reported Outcomes After Spine Surgery. Spine, 44(12), 887-895. doi: 10.1097/BRS.0000000000002964

22.	Oleisky ER, **Pennings JS**, Hills J, Sivaganesan A, Khan I, Call R, Devin CJ & Archer KR. (2019). Comparing different chronic preoperative opioid use definitions on outcomes after spine surgery. The Spine Journal, 19(6), 984-994. doi: 10.1016/j.spinee.2018.12.014

23.	Dabija DI, **Pennings JS**, Archer KR, Ayers GD, Higgins LD, Kuhn JE, Baumgarten KM, Matzkin E, Jain NB. (2019). Which is the best outcome for rotator cuff tears? Clinical Orthopaedics and Related Research®, 477(8), 1869-1878. doi: 10.1097/CORR.0000000000000800

24.	**Pennings JS**, Devin CJ, Khan I, Bydon M, Asher AL, Archer KR. (2019). Prediction of Oswestry Disability Index (ODI) using a PROMIS-29 in a National Sample of Lumbar Spine Surgery Patients. Quality of Life Research, 28(10), 2839-2850. doi:10.1007/s11136-019-02223-8

25.	Rodriguez-Buitrago A, Basem A, Okwumabua E, Enata N, Evans A, **Pennings J**, Karacay B, Rice MJ, Obremskey W. (2019). Hyperglycemia as a Risk Factor for Postoperative Early Wound Infection after Bicondylar Tibial Plateau Fractures: Determining a Predictive Model Based on Four Methods, Injury, 50(11), 2097-2102. doi: 10.1016/j.injury.2019.07.028

26.	Rus, AV, Stativa E, Parris SR, **Pennings JS**, O’Hern Six B, Burcea G, Popa CO. (2019). Awareness of Same-Sex Relationships between Children in Romanian Long-Term Residential Centers. Review of Research and Social Intervention, 66, 6-21. 
27.	Evans P, **Pennings JS**, Samade R, Lovvorn HN, Martus JE. (2019). The Financial Burden of Musculoskeletal Firearm Injuries in Children with and without Concomitant Intra-Cavitary Injuries. Journal of Pediatric Surgery, 55(9), 1754-1760. doi.org/10.1016/j.jpedsurg.2019.09.030

28.	Coronado RA, Devin CJ, **Pennings J**, Aaronson OS, Haug CM, Van Hoy E, Vanston SW, Archer KR. (2019). Safety and Feasibility of an Early Telephone-Supported Home Exercise Program after Anterior Cervical Discectomy and Fusion: A Case Series. Physiotherapy Theory and Practice. Published online 10/30/2019. doi.org/10.1080/09593985.2019.1683921.

29.	Rundell SD, **Pennings JS**, Nian H, Khan I, Asher AL, Devin CJ, Archer KR. (2019). Adding 3-month patient data improves prognostic models of 12-month disability, pain, and satisfaction after specific lumbar spine surgical procedures. The Spine Journal, 20(4), 600-613. doi.org/10.1016/j.spinee.2019.12.010

30.	MARS Group, Wright RW, Huston LJ, Haas AK, Allen CR, Anderson AF, Cooper DE, DeBerardino TM, Dunn WR, Lantz BA, Mann B, Spindler KP, Stuart MJ, Nwosu SK, **Pennings JS**, … Wolf BR, York JJ. (2020). Predictors of clinical outcome following revision anterior cruciate ligament reconstruction. Journal of Orthopaedic Research, 38(6), 1191-1203. doi.org/10.1002/jor.24562.

31.	Khan I, Archer KR, Wanner JP, Bydon M, **Pennings JS**, Sivaganesan A, Knightly JJ, Foley KT, Bisson EF, Shaffrey C, McGirt MJ, Asher AL, Devin CJ. (2020). Trajectory of improvement in myelopathic symptoms from 3- to 12-months following surgery for degenerative cervical myelopathy. Neurosurgery, 86(6), 763-768 doi.org/10.1093/neuros/nyz325

32.	Coronado RA, Devin CJ, **Pennings JS**, Vanston SW, Fenster DE, Hills J, Aaronson OS, Schwarz JP, Stephens BF, Archer KR. (2020). Early self-directed home exercise program after anterior cervical discectomy and fusion: A pilot study. Spine, 45(4), 217-225. doi: 10.1097/BRS.0000000000003239
33.	Asher AM, Oleisky E, Pennings J, Khan I, Sivaganesan A, Devin CJ, Bydon M, Asher Al, Archer KR. (2020). Measuring Clinically Relevant Improvement After Lumbar Spine Surgery: Is It Time for Something New? The Spine Journal, Online ahead of print 1/28/2020. doi.org/10.1016/j.spinee.2020.01.010
34.	Thraikill K, Bunn, RC; Uppuganti S, Ray P, Garrett K, Popescu I, **Pennings, JS**; Fowlkes JL, Nyman, JS. (2020). Genetic ablation of SGLT2 function in mice impairs tissue mineral density but does not affect fracture resistance of bone. Bone, 133, 115254. doi.org/10.1016/j.bone.2020.115254

35.	Hills JM, Carlile CR, Archer KR, Call R, Devin CJ, **Pennings JS** (2020). Duration and dosage of opioids after spine surgery: implications on outcomes at 1 year. Spine, 45(15), 1081-1088. doi: 10.1097/BRS.0000000000003446

36.	Devin CJ, Asher AL, Archer KR, Goyal A, Khan I, Kerezoudis P, Alvi MA, **Pennings JS**, Karacay B, Shaffrey CI, Bisson, EF, Knightly JJ, Mummaneni PV, Foley KT, Bydon, M. (2020). Impact of Dominant Symptom on 12-Month Patient Reported Outcomes for Patients Undergoing Lumbar Spine Surgery: A Quality Outcomes Database Analysis. Neurosurgery, 87(5), 1037-1045. doi.org/10.1093/neuros/nyaa240

37.	Coronado RA, Ehde DM, **Pennings JS**, Vanston SW, Koyama T, Phillips SE, Mathis SL, McGirt MJ, Spengler DM, Aaronson OS, Cheng JS, Devin CJ, Wegner ST, Archer KR. (2020). Psychosocial Mechanisms of Cognitive-Behavioral-Based Physical Therapy Outcomes after Spine Surgery: Preliminary Findings from Mediation Analyses. Physical Therapy (PTJ), 100(10), 1793-1804. doi.org/10.1093/ptj/pzaa112

38.	**Pennings JS**, Khan I, Davidson C, Freitag R, Bydon M, Asher AL, Devin CJ, Archer K. (2020). Using PROMIS-29 to Predict Neck Disability Index (NDI) Scores using a National Sample of Cervical Spine Surgery Patients. The Spine Journal (TSJ), 20(8), 1305-1315. doi.org/10.1016/j.spinee.2020.04.028

39.	Archer KR, Bydon M, Khan I, Nian H, **Pennings JS**, Harrell FE, Sivaganesan A, Chotai S, McGirt JM, Foley KT, Glassman SD, Mummaneni PV, Bisson EF, Knightly JJ Shaffrey C, Asher AL, Devin CJ, QOD Vanguard sites. (2020). Development and validation of cervical prediction models for patient-reported outcomes at 1-year after cervical spine surgery for radiculopathy and myelopathy. Spine, 45(22), 1541-1552. doi: 10.1097/BRS.0000000000003610

40.	**Pennings JS**, Khan I, Hills JM, Coronado RA, Devin CJ, Archer KR. (2020). Classifying Chronic Opioid Use Before Spine Surgery: Comparison of Self-Report and Prescription Drug Monitoring Program (PDMP) Reporting. The Spine Journal (TSJ), 20(11), 1795-1797. doi.org/10.1016/j.spinee.2020.05.548

41.	Archer KR, Haug CM, **Pennings J**. (2020). Comparing Two Programs to Improve Disability, Pain, and Health Among Patients Who Have Had Back Surgery. Washington, DC: Patient-Centered Outcomes Research Institute (PCORI). doi.org/10.25302/04.2020.CER.130601970

42.	Sivaganesan A, Khan I, **Pennings JS**, Roth SG, Nolan E, Asher AL, Bydon M, Devin CJ, Archer KR. (2020). Why are Patients Dissatisfied after Spine Surgery when Improvements in Disability and Pain are Clinically Meaningful? The Spine Journal (TSJ), 20(10), 1535-1543. doi.org/10.1016/j.spinee.2020.06.008

43.	Master H, **Pennings JS**, Coronado RA, Henry AL, O’Brien MT, Haug CM, Skolasky RL, Riley LH, Neuman BJ, Cheng JS, Aaronson OS, Devin CJ, Wegner S, Archer KR. Physical performance tests provide distinct information in both predicting and assessing clinical outcomes following lumbar spine surgery. Spine. Online ahead of print 9/1/2020. doi: 10.1097/BRS.0000000000003665

44.	Coronado RA, Robinette PE, Henry AL, **Pennings JS**, Haug CM, Skolasky RL, Riley LH, Neuman BJ, Cheng JS, Aaronson OS, Devin CJ, Wegener ST, Archer KR. Bouncing back after lumbar spine surgery: early postoperative resilience is associated with 12-month physical function, pain interference, social participation, and disability. The Spine Journal. Online ahead of print 7/28/2020. doi.org/10.1016/j.spinee.2020.07.013

45.	MARS Group, Wright RW, Huston LJ, Haas AK, Allen CR, Anderson AF, Cooper DE, DeBerardino TM, Dunn WR, Lantz BA, Mann B, Spindler KP, Stuart MJ, Nwosu SK, Jacquelyn S **Pennings JS**, … Wolf BR, York JJ. (2020). Meniscal Repair in the Setting of Revision Anterior Cruciate Ligament Reconstruction: Results from the MARS Cohort. The American Journal of Sports Medicine. 48(12), 2978-2985. doi.org/10.1177/0363546520948850

46.	Van Wyngaarden JJ, **Pennings JS**, Jacobs C, Matuszewski P, Noehren B, Archer KR. Reliability and Concurrent Validity of the STarT-Lower Extremity Screening Tool for Patients with Lower Extremity Fracture: A Prospective Study. Arch Phys Med Rehabil. Online ahead of print 10/3/2020.

47.	MARS Group, Brophy, RH, Wright RW, Huston LJ, Haas AK, Nwosu SK, Allen CR, Anderson AF, Cooper DE, DeBerardino TM, Dunn WR, Lantz BA, Mann B, Spindler KP, Stuart MJ, Jacquelyn S **Pennings JS**, … Wolf BR, York JJ. (2020). Rate of Infection Following Revision Anterior Cruciate Ligament Reconstruction and associated patient‐ and surgeon‐ dependent risk factors: Retrospective results from MOON and MARS data collected from 2002 to 2011. Journal of Orthopaedic Research. Online ahead of print 10/1/2020.  https://doi.org/10.1002/jor.24871

48.	Khan I, **Pennings JS**, Devin CJ, Asher AM, Oleisky E, Bydon M, Asher AL, Archer KR. (2020). Clinically Meaningful Improvement Following Cervical Spine Surgery: 30% Reduction vs. Absolute Point-Change MCID Values. Spine. Accepted for publication 10/22/2020. 

<p></br></p> 

## Book Chapters  

1.	Stativa E, Rus AV, Parris SR, Pennings JS, Clocotici O. (2017). Institutional Neglect in Romania’s Long-Term Residential Centers in the 1990s from the Perspective of Children’s Rights. In: Rus A, Parris S, Stativa E. (eds) Child Maltreatment in Residential Care (pp. 27-60). Springer, Cham.  

2.	Rus AV, Stativa E, Parris SR, Pennings JS, Butterfield ME, Lee WC, Gavrilovici O. (2017). Punishment, Peer Exploitation, and Sexual Abuse in Long-Term Romanian Residential Centers: Findings from a Nationally Representative Sample of Institutionalized Children. In: Rus A, Parris S, Stativa E. (eds) Child Maltreatment in Residential Care (pp. 61-86). Springer, Cham.  

3.	Rus AV, Stativa E, Parris SR, Pennings JS, Tibu F, Wenyika R, Burcea G. (2017). Academic Achievement of Romanian Institutionalized Children: A Social–Ecological Approach. In: Rus A, Parris S, Stativa E. (eds) Child Maltreatment in Residential Care (pp. 87-110). Springer, Cham.  

4.	Stativa E, Rus AV, Parris SR, Pennings JS, Simion B, Wenyika R. (2017). The Prevalence of Stunting Among the Romanian Institutionalized Children Placed in Long-Term Institutional Settings in the 1990s. In: Rus A, Parris S, Stativa E. (eds) Child Maltreatment in Residential Care (pp. 111-128). Springer, Cham.  

5.	Griffith DM, Pennings JS, Bruce MA, Ayers, GD. (2019). Measuring the dimensions of African American Manhood: A factor analysis. In Griffith DM, Bruce MA, Thorpe Jr RJ. (Eds.), Men’s Health Equity: A Handbook. New York, NY: Routledge.  


<p></br></p> 

## Grants
**<span style="color:#2780e3">Ongoing Research Support</span>**  

#### Registry for the Advancement of Deep Brain Stimulation Therapy in Parkinson’s Disease “RAD-PD” (PI: Pennings)
>#### Role: Principal Investigator 
##### 2020 - Present: Funded by Neuropoint Alliance (NPA)

#### Integration of an Internet Self-Management Program into Physical Therapy for Chronic Spine Pain (PI: Coronado)
>#### Role: Co-Investigator 
##### 2019 - Present: Vanderbilt Center for Musculoskeletal Research Seed Grant

#### Diabetes-Related Changes Affecting Bone Quality (PI: Nyman)
>#### Role: Co-Investigator 
##### 2019 - Present: Funded by PCORI

#### Revision ACL Reconstructions: A Comparative Effectiveness Treatment Study (PI: Wright)
>#### Role: Co-Investigator
##### 2017 - Present: Funded by NIH/NIAMS (RO1)

#### Mighty Men: A Faith-based Weight Loss Program to Reduce Cancer Disparities (PI: Griffith)
>#### Role: Co-Investigator 
##### 2016 - Present: Funded by the American Cancer Society

#### NIH/NIMHD Vanderbilt-Miami-Meharry Center of Excellence in Precision Medicine and Population Health (PI: Wilkins)
>#### Role: Biostatistician 
##### 2016 - Present: Funded by NIH/NIMHD (U54)

#### Improving ACL Reconstruction Return to Play Outcomes through Psychologically Informed Rehabilitation (PI: Archer)
>#### Role: Co-Investigator 
##### 2018 - Present: American Orthopaedic Society Sports Medicine 

**<span style="color:#2780e3">Completed Research Support</span>**

#### Quality and Outcomes Database (PI: Archer)
>#### Role: Associate Director 
##### 2015 - 2020: Funded by Neuropoint Alliance (NPA)

#### Comparative Effectiveness of Postoperative Management for Degenerative Spinal Conditions (PI: Archer)
>#### Role: Co-Investigator 
##### 2014 - 2018: Funded by PCORI

#### Improving Trauma Outcomes: A Goal Management Approach (PI: Archer)
>#### Role: Biostatistician
##### 2012 - 2016: Funded by National Institute on Disability and Rehabilitation Research  

#### Using Tailoring and Technology to Promote Health Equity in African American Men (PI: Griffith, PhD)
>#### Role: Biostatistician
##### 2015 - 2017: Funded by the AETNA Foundation 

#### Project LiiNK: Let's Inspire Innovation 'N Kids (PI: Rhea) 
>#### Role: assist with grant writing, research design, data management protocols, statistical analysis, statistical write up of results for reports and manuscripts
#### 2013 - 2017: Funded by Texas Christian University, The Miles Foundation, The Walsh Foundation, Alan C. Fox, and others

#### Testing Two Global Models to Prevent Violence Against Women and Children: Methods and Policy Implications for a Seven Year Prospective Study (PI: McFarlane)
>#### Role: Research design, instrumentation development, data preparation, scoring, statistical analysis for program evaluation, stakeholder reports, manuscript preparation
##### 2011 - 2016: Funded by The Houston Endowment

#### A School-Based Intervention to Reduce Stigma and Promote Mental-Health Service Use (PI: Link)
>#### Role: Research design, statistical analysis
##### 2011 - 2015: Funded by R-01 NIH/NIMH Submission (General)

#### Attitudes and Behaviors of Youth (PI: Reesor)
>#### Role: Research design, statistical analysis
##### 2006 - 2013: Funded by Maclellan Foundation and Global Ministries - Book of Hope International

#### Measuring the Effectiveness of iMatter Training on South African School Children (PI: York &  Ecker)
>#### Role: Research design, statistical analysis for program evaluation
##### 2009 - 2010: Funded by US President's Emergency Plan for AIDS Relief (PEPFAR)

<p><br></p> 


## Dissertation & Thesis

Dissertation (2009): The Effects of a Touch Intervention on Nurturing Touch, Family Functioning, and Child Behavior  

Thesis (2005): Effects of maternal deprivation on problem behavior in post-institutionalized children  

Undergraduate Honors Thesis (2001): Self-Perceptions and Physical Education
